### PR TITLE
update ring-core to 1.9.4

### PR DESCRIPTION
**Pull request by antonmos**

### CODE REVIEW

**Comment by ikitommi** [comment]
Thanks!

**Comment by antonmos** [comment]
Would you mind making a release with this change? Thanks!

**Comment by ikitommi** [comment]
I'll ping if someone could do &/ automate it.

**Comment by opqdonut** [comment]
I'm on it!

**Comment by opqdonut** [comment]
https://clojars.org/metosin/ring-http-response/versions/0.9.3

**Pull request merged**
