### PR TITLE
Generate response and status code from dev template

### LINKED ISSUE #2: Vars for http-status codes
* own namespace, with vars for all status-codes
```clojure
(require '[ring.util.http-code :as code])

code/forbidden
; 403
```

* ide support/autocomplete for codes
* would be easier to use response-codes in conjunction with response-functions, for example with compojure-api:

```clojure
(require '[ring.util.http-response :refer :all])
(require '[ring.util.http-code :as code])

(POST* "/number" []
  :responses    {code/forbidden {:message String}
  (forbidden {:message "difference is negative"}))
```

### PR DESCRIPTION
**Pull request by frankiesardo**
Fixes #2 #3 #5
This also fixes a minor bug on response 205

### CODE REVIEW

**Comment by frankiesardo** [comment]
I left out most of the wordings, you guys let me know what you think. 

Other things to consider:
- We should probably generate the source code as a build step.
- We could probably generate the test code as well, but then, hey, what are we testing?

**Comment by ikitommi** [comment]
Looks great! 

Seems to fix also few bugs in the (original Spray) definitions. Did a small spike how to imports vars without Potemkin, so we'll have one dependency less. I think it's important to have the var meta-data in place, to get the docs & "jump to source" too.

**Comment by ikitommi** [comment]
had to add Potemkin back. Got working without it, but using Cursive, which currently can track potemkin imports, but no my custom ones. Will try to remove it later.

**Comment by frankiesardo** [comment]
I don't see any issue about leaving potemkin in, it was just a nice optimisation if it was easy to get rid of it :+1:

**Pull request merged**
