### PR TITLE
Remove Slingshot in docs

### PR DESCRIPTION
**Pull request by tentamen**

### CODE REVIEW

**Comment by Deraen** [comment]
Hi,

The real code is generated from templates in templates folder, please fix the comment here: https://github.com/metosin/ring-http-response/blob/master/templates/http-response.mustache#L40

and run `(generate!)` in REPL. https://github.com/metosin/ring-http-response/blob/master/dev/user.clj#L109

**Comment by tentamen** [comment]
ah, I amend the commit & update template file.

**Comment by tentamen** [comment]
on travis config file, lein script should be `lein` intead of `lein2`?

**Comment by Deraen** [comment]
Travis conf should be fixed in master now, you can merge master here or rebase this.

**Comment by Deraen** [comment]
Thanks

**Pull request merged**
