### PR TITLE
add teapot functionality

### PR DESCRIPTION
**Pull request by AndreaCrotti**
From https://www.rfc-editor.org/rfc/rfc2324#section-2.3.2

### CODE REVIEW

**Comment by ikitommi** [comment]
thanks! Added development instructions - all code is generated, see https://github.com/metosin/ring-http-response?tab=readme-ov-file#adding-new-http-status-codes.

**Comment by ikitommi** [comment]
could you change the implementation to use the code generation? there are 3 namespaces that are effected.

**Comment by AndreaCrotti** [comment]
> could you change the implementation to use the code generation? there are 3 namespaces that are effected. 

Looks like you've done it already? Just an issue with the tests but looks good to me otherwise

**Comment by ikitommi** [comment]
tested if that works, didn't, but fixed it. I copied your texts to `dev/user.clj` + `lein repl`+ `(generate!)`.

**Comment by ikitommi** [comment]
thanks!

**Pull request merged**
